"use client";

import { useMemo } from "react";
import { generateAvatar } from "@/lib/avatar";
import { getDomain } from "@/lib/types";
import PixelButton from "./PixelButton";

interface PlayerTicketProps {
  name: string;
  email: string;
  domainId: string;
  playerId: string;
}

/**
 * Builds the ticket as a single self-contained SVG string. We use one SVG for
 * both on-screen display and PNG export so what you see is what you download.
 */
function buildTicketSVG({
  name,
  domainId,
  playerId,
}: {
  name: string;
  domainId: string;
  playerId: string;
}): string {
  const domain = getDomain(domainId);
  const color = domain?.color ?? "#39ff14";
  const codename = domain?.codename ?? "Free Agent";
  const { grid } = generateAvatar(playerId || name);

  // Avatar block, top-left.
  const ax = 34;
  const ay = 70;
  const cell = 14;
  let avatarRects = `<rect x="${ax - 6}" y="${ay - 6}" width="${
    8 * cell + 12
  }" height="${8 * cell + 12}" fill="#05130a" stroke="${color}" stroke-width="3"/>`;
  grid.forEach((row, y) =>
    row.forEach((on, x) => {
      if (on)
        avatarRects += `<rect x="${ax + x * cell}" y="${
          ay + y * cell
        }" width="${cell}" height="${cell}" fill="${color}"/>`;
    })
  );

  // Barcode strip.
  let bars = "";
  let bx = 34;
  for (let i = 0; i < 46; i++) {
    const w = (i % 3) + 1;
    if (i % 2 === 0) {
      bars += `<rect x="${bx}" y="330" width="${w * 2}" height="34" fill="#0a0118"/>`;
    }
    bx += w * 2 + 2;
  }

  const safeName = (name || "PLAYER ONE").toUpperCase().slice(0, 16);

  return `
<svg xmlns="http://www.w3.org/2000/svg" width="440" height="400" viewBox="0 0 440 400" font-family="'Press Start 2P', monospace">
  <defs>
    <linearGradient id="tk" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#160b2e"/>
      <stop offset="1" stop-color="#0a0118"/>
    </linearGradient>
  </defs>
  <rect x="6" y="6" width="428" height="388" rx="10" fill="url(#tk)" stroke="${color}" stroke-width="4"/>
  <rect x="6" y="6" width="428" height="46" rx="0" fill="${color}"/>
  <text x="220" y="37" text-anchor="middle" font-size="16" fill="#000">PLAYER ID</text>

  ${avatarRects}

  <text x="176" y="80" font-size="9" fill="#7a6aa0">NAME</text>
  <text x="176" y="104" font-size="13" fill="#e6f7ff">${safeName}</text>

  <text x="176" y="140" font-size="9" fill="#7a6aa0">DOMAIN</text>
  <text x="176" y="164" font-size="12" fill="${color}">${codename.toUpperCase()}</text>

  <text x="176" y="200" font-size="9" fill="#7a6aa0">PLAYER No.</text>
  <text x="176" y="224" font-size="12" fill="#ffe600">#${playerId.slice(0, 8).toUpperCase()}</text>

  <text x="34" y="270" font-size="9" fill="#7a6aa0">CREDITS</text>
  <text x="120" y="270" font-size="9" fill="#39ff14">∞ · 1 UP</text>

  <text x="220" y="300" text-anchor="middle" font-size="9" fill="#ff00d4">◆ INSERT COIN TO CONTINUE ◆</text>
  ${bars}
  <text x="220" y="384" text-anchor="middle" font-size="7" fill="#5a4a7a">CLUB RECRUITMENT ARCADE · ADMIT ONE</text>
</svg>`.trim();
}

export default function PlayerTicket({
  name,
  email,
  domainId,
  playerId,
}: PlayerTicketProps) {
  const svg = useMemo(
    () => buildTicketSVG({ name, domainId, playerId }),
    [name, domainId, playerId]
  );

  const download = async () => {
    const blob = new Blob([svg], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const img = new Image();
    img.crossOrigin = "anonymous";
    await new Promise<void>((resolve, reject) => {
      img.onload = () => resolve();
      img.onerror = () => reject(new Error("render failed"));
      img.src = url;
    });
    const scale = 2;
    const canvas = document.createElement("canvas");
    canvas.width = 440 * scale;
    canvas.height = 400 * scale;
    const ctx = canvas.getContext("2d");
    if (ctx) {
      ctx.imageSmoothingEnabled = false;
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    }
    URL.revokeObjectURL(url);
    const png = canvas.toDataURL("image/png");
    const a = document.createElement("a");
    a.href = png;
    a.download = `player-ticket-${(name || "player").replace(/\s+/g, "-").toLowerCase()}.png`;
    a.click();
  };

  const share = async () => {
    const text = `I just joined the Club Recruitment Arcade as ${
      name || "a new player"
    }! 🕹️ #InsertCoin`;
    try {
      if (navigator.share) {
        await navigator.share({ title: "Player ID", text });
      } else {
        await navigator.clipboard.writeText(text);
        alert("Copied share text to clipboard!");
      }
    } catch {
      /* user cancelled */
    }
  };

  return (
    <div className="flex flex-col items-center gap-4">
      <div
        className="w-full max-w-[440px]"
        // The ticket SVG is generated by us from local data — safe to inline.
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      <div className="flex flex-wrap justify-center gap-3">
        <PixelButton color="#39ff14" onClick={download}>
          ⬇ Download
        </PixelButton>
        <PixelButton color="#00f0ff" onClick={share}>
          ⤴ Share
        </PixelButton>
      </div>
    </div>
  );
}
